// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_JumpAbility","status":true,"description":"Allows the player to jump by pressing a button.","parameters":{"Key":"c","Jump Distance":"2","Blocking Regions":"255,254","Jump Sound":"Jump1, 80, 150"}},
{"name":"OrangeHud","status":true,"description":"Creates a custom HUD based on the params","parameters":{"DefaultFontFace":"Verdana","DefaultFontSize":"18","DefaultFontColor":"#FFFFFF","DefaultFontItalic":"false","HudWidth":"0","HudHeight":"0","HudX":"0","HudY":"0","HudOpacity":"0","SwitchId":"0"}},
{"name":"OrangeHudLine","status":true,"description":"OrangeHudLine 1.5 - Adds a new Variable to Orange Hud","parameters":{"GroupName":"main","Pattern":"%1 Points","VariableId":"1","SwitchId":"0","X":"","Y":"","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","ScriptPattern":"","VariableX":"0","VariableY":"0"}},
{"name":"SRD_TitleMapBackground","status":true,"description":"Allows developers to set a map to be used as the background of their title screen.","parameters":{"Map ID":"15"}}
];
